[workspace]
members = [
    "src/victus-max-daemon",
    "src/victus-max-cli",
    "src/victus-max-tray",
    "src/victus-max-gui",
    "src/victus-max-overlay",
    "src/victus-max-types",
]
resolver = "2"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
